global:
  name: stdl
  namespace: media
persistence:
  storageClass: nfs-main1
  mountPath: /mnt/nfs
vault:
  mount: kube
  refreshAfter: 30s
  proton:
    path: platform/proton
    version: 1
    secretName: stdl-proton-secret
  nordvpn1:
    path: platform/nordvpn1
    version: 1
    secretName: stdl-nordvpn1-secret
  nordvpn2:
    path: platform/nordvpn2
    version: 1
    secretName: stdl-nordvpn2-secret
