global:
  namespace: media
vault:
  mount: kube
  version: 1
  refreshAfter: 30s
secrets:
  auth:
    path: media/recnode/auth
    secretName: recnode-auth
  fs:
    path: media/recnode/fs
    secretName: recnode-fs
  queue:
    path: media/recnode/queue
    secretName: recnode-queue
  redisServer:
    path: media/recnode/redis/server
    secretName: recnode-redis-server
  redisClient:
    path: media/recnode/redis/client
    secretName: recnode-redis-client
