global:
  namespace: media
vault:
  mount: kube
  version: 1
  refreshAfter: 30s
secrets:
  queue:
    path: media/stdl/queue
    secretName: stdl-queue
  fs:
    path: media/stdl/fs
    secretName: stdl-fs
