global:
  name: stdl
  namespace: media
persistence:
  storageClass: nfs-main1
  mountPath: /mnt/nfs
vault:
  mount: kube
  refreshAfter: 30s
  proton:
    path: platform/proton
    version: 1
    secretName: stdl-proton-secret
  nordvpn:
    path: platform/nordvpn
    version: 1
    secretName: stdl-nordvpn-secret
