global:
  namespace: media
vault:
  mount: kube
  version: 1
  refreshAfter: 30s
secrets:
  auth:
    path: media/stdl/auth
    secretName: stdl-auth
  fs:
    path: media/stdl/fs
    secretName: stdl-fs
  queue:
    path: media/stdl/queue
    secretName: recnode-queue
  redisServer:
    path: media/stdl/redis/server
    secretName: stdl-redis-server
  redisClient:
    path: media/stdl/redis/client
    secretName: stdl-redis-client
