apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.name }}-{{ .Values.global.suffix }}
  namespace: {{ .Values.global.namespace }}
data:
  client.ovpn: |
{{ .Files.Get .Values.configmap.confFilePath | indent 4 }}
