apiVersion: batch/v1
kind: Job
metadata:
  name: stdl-{{ .Values.jobSuffix }}
spec:
  template:
    spec:
      containers:
        - name: stdl
          image: ghcr.io/rwiv/stdl:latest
          env:
            - name: CHZZK_UID
              value: {{ .Values.chzzk.uid }}
            - name: OUT_DIR
              value: {{ .Values.file.outDir }}
            - name: HTTP_COOKIES
              value: {{ .Values.chzzk.cookies | quote }}
            - name: PY_ENV
              value: prod
          volumeMounts:
            - name: nfs-volume
              mountPath: {{ .Values.file.mountPath }}
      restartPolicy: Never
      volumes:
        - name: nfs-volume
          nfs:
            path: {{ .Values.nfs.path }}
            server: {{ .Values.nfs.server }}
  backoffLimit: 0
