global:
  name: recnode
  namespace: media
  suffix: proton
image:
  repository: harbor.rwiv.xyz/private/recnode
  tag: 0.0.0
  pullSecret: image-pull-secret
vault:
  mount: kube
  refreshAfter: 30s
  proton:
    path: platform/proton
    version: 1
    secretName: recnode-proton-secret
gluetun:
  repository: qmcgaw/gluetun
  tag: v3.40
  provider: protonvpn
  countries: Korea
persistence:
  nfs:
    pvcName: recnode
    storageClass: nfs-main1
    mountPath: /mnt/nfs
    requests: 2000Gi
resources:
  requests:
    cpu: 40m
    memory: 200Mi
workflow:
  webhook:
    endpoint: /recnode-proton
    port: 12000
    method: POST
secret:
  userKey: user
  passwordKey: password
app:
  rabbitmq:
    host: rabbitmq.infra.svc.cluster.local
    port: 5672
    username: admin
    secretName: rabbitmq-main
    passwordKey: password
  tmpDirPath: /app/tmp
