global:
  name: recnode
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/recnode
  tag: 0.0.0
  pullSecret: image-pull-secret
persistence:
  nfs:
    pvcName: recnode
    storageClass: nfs-main1
    mountPath: /mnt/nfs
    requests: 2000Gi
resources:
  requests:
    cpu: 40m
    memory: 200Mi
workflow:
  webhook:
    endpoint: /recnode
    port: 12000
    method: POST
app:
  rabbitmq:
    host: rabbitmq.infra.svc.cluster.local
    port: 5672
    username: admin
    secretName: rabbitmq-main
    passwordKey: password
  tmpDirPath: /app/tmp
