global:
  name: stdl
  namespace: media
  suffix: nordvpn
image:
  repository: harbor.rwiv.xyz/private/stdl
  tag: 0.5.1
  pullSecret: image-pull-secret
vault:
  mount: kube
  refreshAfter: 30s
  nordvpn:
    path: platform/nordvpn/credentials
    version: 1
    secretName: stdl-nordvpn-secret
gluetun:
  repository: qmcgaw/gluetun
  tag: v3.40
persistence:
  nfs:
    pvcName: stdl
    storageClass: nfs-main1
    mountPath: /mnt/nfs
    requests: 2000Gi
resources:
  requests:
    cpu: 40m
    memory: 200Mi
workflow:
  webhook:
    endpoint: /stdl-sub
    port: 12000
    method: POST
ovpn:
  confFilePath: conf/client.ovpn
  userKey: username
  passwordKey: password
app:
  rabbitmq:
    host: rabbitmq.infra.svc.cluster.local
    port: 5672
    username: admin
    secretName: rabbitmq-main
    passwordKey: password
  tmpDirPath: /app/tmp
