apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
      sub: {{ .Values.metadata.name }}
      {{ if .Values.nodeAlias }}
      node: {{ .Values.nodeAlias }}
      {{ end }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
        sub: {{ .Values.metadata.name }}
        {{ if .Values.nodeAlias }}
        node: {{ .Values.nodeAlias }}
        {{ end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{ if .Values.nodeAlias }}
      nodeSelector:
        alias: {{ .Values.nodeAlias }}
      {{ end }}
      containers:
        - name: {{ .Values.server.containerName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          workingDir: "/app"
          command: ["python", "-m", "stdl", "proxy"]
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          env:
            - name: PY_ENV
              value: prod
            - name: SERVER_PORT
              value: "{{ .Values.server.service.targetPort }}"
            - name: FS_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.fs.secretName }}
                  key: {{ .Values.server.fs.fsNameKey }}
            - name: FS_CONFIG_PATH
              value: "/mnt/fs-configs/{{ .Values.server.fs.confKey }}"
            - name: PROXY_ENABLED
              value: "true"
          volumeMounts:
            - name: fs-configs
              mountPath: "/mnt/fs-configs/{{ .Values.server.fs.confKey }}"
              subPath: {{ .Values.server.fs.confKey }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: fs-configs
          secret:
            secretName: {{ .Values.server.fs.secretName }}
