apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    app: {{ .Values.metadata.appName }}
    sub: {{ .Values.metadata.name }}
    {{ if .Values.nodeAlias }}
    node: {{ .Values.nodeAlias }}
    {{ end }}
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
