global:
  name: stdl-sep
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/stdl
  tag: 0.1.5
  pullSecret: image-pull-secret
persistence:
  mountPath: /mnt/nfs
jobSuffix: foo
chzzk:
  uid: foo
  once: false
