global:
  name: stdl-sep
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/stdl
  tag: 0.1.21
  pullSecret: image-pull-secret
persistence:
  nfs:
    mountPath: /mnt/nfs
  ceph:
    mountPath: /mnt/ceph
    namePrefix: stdl-once-ceph-
    storageClass: rook-ceph-block
    requests: 200Gi
resources:
  requests:
    cpu: 40m
    memory: 200Mi
configMap:
  namePrefix: stdl-once-conf-
  mountPath: /app/conf
secret:
  userKey: user
  passwordKey: password
app:
  reqType: chzzk_live
  startDelayMs: 0
chzzk:
  live:
    uid: foo
    once: false
  video:
    noList: []
    isParallel: true
    parallelNum: 3
    nonParallelDelayMs: 200
  cookies: ~
afreeca:
  video:
    noList: []
    isParallel: true
    parallelNum: 3
    nonParallelDelayMs: 200
  cookies: ~
jobSuffix: foo
