apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.name }}-ovpn-{{ .Values.jobSuffix }}
  namespace: {{ .Values.global.namespace }}
data:
  client.ovpn: |
{{ .Files.Get .Values.ovpn.confFilePath | indent 4 }}
