services:
  gluetun1:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun1
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${SERVER_PORT1}:9083"
    volumes:
      - "${OPENVPN_CONFIG_PATH}:/ovpn/client.ovpn"
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - "OPENVPN_USER=${OPENVPN_USER}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
      - OPENVPN_CUSTOM_CONFIG=/ovpn/client.ovpn
  gluetun2:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun2
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${SERVER_PORT2}:9083"
    volumes:
      - "${OPENVPN_CONFIG_PATH}:/ovpn/client.ovpn"
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - "OPENVPN_USER=${OPENVPN_USER}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
      - OPENVPN_CUSTOM_CONFIG=/ovpn/client.ovpn
