services:
  stdl:
    image: harbor.rwiv.xyz/private/stdl:0.4.8
    container_name: stdl
    environment:
      PY_ENV: prod
      SEG_SIZE_MB: "${SEG_SIZE_MB}"
      STREAM_TIMEOUT_SEC: "${STREAM_TIMEOUT_SEC}"
      WATCHER_ENABLED: "false"

      FS_NAME: "${FS_NAME}"
      FS_CONFIG_PATH: /app/fs_conf.yaml

      OUT_DIR_PATH: /app/out
      TMP_DIR_PATH: /app/tmp

      AMQP_HOST: "${AMQP_HOST}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
    entrypoint: python -m stdl server
    ports:
      - "${SERVER_PORT}:9083"
    volumes:
      - "${FS_CONFIG_PATH}:/app/fs_conf.yaml"
      - "${OUT_DIR_PATH}:/app/out"
      - "${TMP_DIR_PATH}:/app/tmp"
