services:
  stdl:
    image: harbor.rwiv.xyz/private/stdl:0.3.3
    container_name: stdl
    environment:
      PY_ENV: prod
      FS_NAME: "${FS_NAME}"
      FS_CONFIG_PATH: /app/fs_conf.yaml
      OUT_DIR_PATH: /app/out
      TMP_DIR_PATH: /app/tmp
      AMQP_HOST: "${AMQP_HOST}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
    entrypoint: python -m stdl server
    volumes:
      - "${FS_CONFIG_PATH}:/app/fs_conf.yaml"
      - "${OUT_DIR_PATH}:/app/out"
      - "${TMP_DIR_PATH}:/app/tmp"
