services:
  stdl:
    image: stdl:latest
    container_name: stdl
    environment:
      PY_ENV: prod
      CONFIG_PATH: /app/conf.yaml
      WATCHER_ENABLED: "${WATCHER_ENABLED}"

      FS_NAME: "${FS_NAME}"
      FS_CONFIG_PATH: /app/fs_conf.yaml
      OUT_DIR_PATH: /app/out
      TMP_DIR_PATH: /app/tmp
      SEG_SIZE_MB: "${SEG_SIZE_MB}"
      AMQP_HOST: "${AMQP_HOST}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
    volumes:
      - "${FS_CONFIG_PATH}:/app/fs_conf.yaml"
      - "${OUT_DIR_PATH}:/app/out"
      - "${TMP_DIR_PATH}:/app/tmp"
      - "${CONFIG_PATH}:/app/conf.yaml"
