services:
  stdl:
    image: stdl:latest
    container_name: stdl
    environment:
      OUT_DIR_PATH: /app/out
      PY_ENV: dev
    volumes:
      - ../dev/event.json:/etc/jobsink-event/event
      - ../dev/out:/app/out
