services:
  stdl:
    image: stdl:latest
    container_name: stdl
    working_dir: /app
    entrypoint: "python -u main.py"
    environment:
      CONFIG_PATH: "${CONFIG_PATH}"
      AFREECA_USERNAME: "${AFREECA_USERNAME}"
      AFREECA_PASSWORD: "${AFREECA_PASSWORD}"
      PY_ENV: "${PY_ENV}"
    volumes:
      - ../stdl:/app/stdl
      - ../main.py:/app/main.py
      - ../dev:/app/dev
