services:
  gluetun:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "9083:9083"
    volumes:
      - "${OPENVPN_CONFIG_PATH}:/ovpn/client.ovpn"
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - "OPENVPN_USER=${OPENVPN_USER}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
      - OPENVPN_CUSTOM_CONFIG=/ovpn/client.ovpn
      - DNS_KEEP_NAMESERVER=true
  recnode-vpn:
    image: recnode:latest
    container_name: recnode-vpn
    environment:
      PY_ENV: prod
      SEG_SIZE_MB: "${SEG_SIZE_MB}"
      PROXY_ENABLED: "true"
      PROXY_ENDPOINT: "http://recnode-proxy:9084"

      FS_NAME: "${FS_NAME}"
      FS_CONFIG_PATH: /app/fs_conf.yaml

      TMP_DIR_PATH: /app/tmp

      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_CA_PATH: /app/ca.crt
    entrypoint: python -m recnode server
    volumes:
      - "${FS_CONFIG_PATH}:/app/fs_conf.yaml"
      - "${TMP_DIR_PATH}:/app/tmp"
      - "${REDIS_CA_PATH}:/app/ca.crt"
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: container:gluetun
  recnode-proxy:
    image: recnode:latest
    container_name: recnode-proxy
    environment:
      PY_ENV: prod
      SERVER_PORT: "9084"
      PROXY_ENABLED: "true"

      FS_NAME: "${FS_NAME}"
      FS_CONFIG_PATH: /app/fs_conf.yaml
    entrypoint: python -m recnode proxy
    volumes:
      - "${FS_CONFIG_PATH}:/app/fs_conf.yaml"
