services:
  gluetun2:
    image: qmcgaw/gluetun:v3.40
    container_name: gluetun2
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${SERVER_PORT_VPN2}:9083"
    volumes:
      - "${OPENVPN_CONFIG_PATH}:/ovpn/client.ovpn"
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - "OPENVPN_USER=${OPENVPN_USER}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
      - OPENVPN_CUSTOM_CONFIG=/ovpn/client.ovpn
    labels:
      app: gluetun
      host: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        labels: app,host
        tag: "container_image={{.ImageName}},container_name={{.Name}}"
  stdl-vpn2:
    image: harbor.rwiv.xyz/private/stdl:0.5.4
    container_name: stdl-vpn2
    environment:
      PY_ENV: prod
      SEG_SIZE_MB: "${SEG_SIZE_MB}"
      WATCHER_ENABLED: "true"

      FS_NAME: "${FS_NAME}"
      FS_CONFIG_PATH: /app/fs_conf.yaml

      TMP_DIR_PATH: /app/tmp

      AMQP_HOST: "${AMQP_HOST}"
      AMQP_PORT: "${AMQP_PORT}"
      AMQP_USERNAME: "${AMQP_USERNAME}"
      AMQP_PASSWORD: "${AMQP_PASSWORD}"
    entrypoint: python -m stdl server
    volumes:
      - "${FS_CONFIG_PATH}:/app/fs_conf.yaml"
    depends_on:
      gluetun2:
        condition: service_healthy
    network_mode: container:gluetun2
    labels:
      app: stdl
      host: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        labels: app,host
        tag: "container_image={{.ImageName}},container_name={{.Name}}"
