services:
  recnode-server1:
    image: recnode:latest
    container_name: recnode-server1
    environment:
      PY_ENV: prod
      SERVER_PORT: "${SERVER_PORT}"
      SERVER_API_TOKEN: "${SERVER_API_TOKEN}"
      SEG_SIZE_MB: "${SEG_SIZE_MB}"

      FS_NAME: "${FS_NAME}"
      FS_CONFIG_PATH: /app/fs_conf.yaml

      TMP_DIR_PATH: /app/tmp
      OUT_DIR_PATH: /app/out

      M3U8_RETRY_LIMIT: "${M3U8_RETRY_LIMIT}"
      M3U8_TIMEOUT_SEC: "${M3U8_TIMEOUT_SEC}"
      SEG_TIMEOUT_SEC: "${SEG_TIMEOUT_SEC}"
      SEG_PARALLEL_RETRY_LIMIT: "${SEG_PARALLEL_RETRY_LIMIT}"
      SEG_FAILURE_THRESHOLD_RATIO: "${SEG_FAILURE_THRESHOLD_RATIO}"
      INTERVAL_WAIT_WEIGHT_SEC: "${INTERVAL_WAIT_WEIGHT_SEC}"
      INTERVAL_MIN_TIME_SEC: "${INTERVAL_MIN_TIME_SEC}"

      REDIS_MASTER_HOST: "${REDIS_MASTER_HOST}"
      REDIS_MASTER_PORT: "${REDIS_MASTER_PORT}"
      REDIS_REPLICA_HOST: "${REDIS_REPLICA_HOST}"
      REDIS_REPLICA_PORT: "${REDIS_REPLICA_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_POOL_SIZE_LIMIT: "${REDIS_POOL_SIZE_LIMIT}"

      REDIS_LOCK_EXPIRE_SEC: "${REDIS_LOCK_EXPIRE_SEC}"
      REDIS_LOCK_WAIT_SEC: "${REDIS_LOCK_WAIT_SEC}"
      REDIS_SEG_EXPIRE_SEC: "${REDIS_SEG_EXPIRE_SEC}"
      REDIS_LIVE_EXPIRE_SEC: "${REDIS_LIVE_EXPIRE_SEC}"
    entrypoint: python -m recnode server
    ports:
      - "13201:${SERVER_PORT}"
    volumes:
      - "${FS_CONFIG_PATH}:/app/fs_conf.yaml"
      - "${OUT_DIR_PATH}:/app/out"
      - "../recnode:/app/recnode"
  recnode-server2:
    image: recnode:latest
    container_name: recnode-server2
    environment:
      PY_ENV: prod
      SERVER_PORT: "${SERVER_PORT}"
      SERVER_API_TOKEN: "${SERVER_API_TOKEN}"
      SEG_SIZE_MB: "${SEG_SIZE_MB}"

      FS_NAME: "${FS_NAME}"
      FS_CONFIG_PATH: /app/fs_conf.yaml

      TMP_DIR_PATH: /app/tmp
      OUT_DIR_PATH: /app/out

      M3U8_RETRY_LIMIT: "${M3U8_RETRY_LIMIT}"
      M3U8_TIMEOUT_SEC: "${M3U8_TIMEOUT_SEC}"
      SEG_TIMEOUT_SEC: "${SEG_TIMEOUT_SEC}"
      SEG_PARALLEL_RETRY_LIMIT: "${SEG_PARALLEL_RETRY_LIMIT}"
      SEG_FAILURE_THRESHOLD_RATIO: "${SEG_FAILURE_THRESHOLD_RATIO}"
      INTERVAL_WAIT_WEIGHT_SEC: "${INTERVAL_WAIT_WEIGHT_SEC}"
      INTERVAL_MIN_TIME_SEC: "${INTERVAL_MIN_TIME_SEC}"

      REDIS_MASTER_HOST: "${REDIS_MASTER_HOST}"
      REDIS_MASTER_PORT: "${REDIS_MASTER_PORT}"
      REDIS_REPLICA_HOST: "${REDIS_REPLICA_HOST}"
      REDIS_REPLICA_PORT: "${REDIS_REPLICA_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_POOL_SIZE_LIMIT: "${REDIS_POOL_SIZE_LIMIT}"

      REDIS_LOCK_EXPIRE_SEC: "${REDIS_LOCK_EXPIRE_SEC}"
      REDIS_LOCK_WAIT_SEC: "${REDIS_LOCK_WAIT_SEC}"
      REDIS_SEG_EXPIRE_SEC: "${REDIS_SEG_EXPIRE_SEC}"
      REDIS_LIVE_EXPIRE_SEC: "${REDIS_LIVE_EXPIRE_SEC}"
    entrypoint: python -m recnode server
    ports:
      - "13202:${SERVER_PORT}"
    volumes:
      - "${FS_CONFIG_PATH}:/app/fs_conf.yaml"
      - "${OUT_DIR_PATH}:/app/out"
      - "../recnode:/app/recnode"
  recnode-server3:
    image: recnode:latest
    container_name: recnode-server3
    environment:
      PY_ENV: prod
      SERVER_PORT: "${SERVER_PORT}"
      SERVER_API_TOKEN: "${SERVER_API_TOKEN}"
      SEG_SIZE_MB: "${SEG_SIZE_MB}"

      FS_NAME: "${FS_NAME}"
      FS_CONFIG_PATH: /app/fs_conf.yaml

      TMP_DIR_PATH: /app/tmp
      OUT_DIR_PATH: /app/out

      M3U8_RETRY_LIMIT: "${M3U8_RETRY_LIMIT}"
      M3U8_TIMEOUT_SEC: "${M3U8_TIMEOUT_SEC}"
      SEG_TIMEOUT_SEC: "${SEG_TIMEOUT_SEC}"
      SEG_PARALLEL_RETRY_LIMIT: "${SEG_PARALLEL_RETRY_LIMIT}"
      SEG_FAILURE_THRESHOLD_RATIO: "${SEG_FAILURE_THRESHOLD_RATIO}"
      INTERVAL_WAIT_WEIGHT_SEC: "${INTERVAL_WAIT_WEIGHT_SEC}"
      INTERVAL_MIN_TIME_SEC: "${INTERVAL_MIN_TIME_SEC}"

      REDIS_MASTER_HOST: "${REDIS_MASTER_HOST}"
      REDIS_MASTER_PORT: "${REDIS_MASTER_PORT}"
      REDIS_REPLICA_HOST: "${REDIS_REPLICA_HOST}"
      REDIS_REPLICA_PORT: "${REDIS_REPLICA_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_POOL_SIZE_LIMIT: "${REDIS_POOL_SIZE_LIMIT}"

      REDIS_LOCK_EXPIRE_SEC: "${REDIS_LOCK_EXPIRE_SEC}"
      REDIS_LOCK_WAIT_SEC: "${REDIS_LOCK_WAIT_SEC}"
      REDIS_SEG_EXPIRE_SEC: "${REDIS_SEG_EXPIRE_SEC}"
      REDIS_LIVE_EXPIRE_SEC: "${REDIS_LIVE_EXPIRE_SEC}"
    entrypoint: python -m recnode server
    ports:
      - "13203:${SERVER_PORT}"
    volumes:
      - "${FS_CONFIG_PATH}:/app/fs_conf.yaml"
      - "${OUT_DIR_PATH}:/app/out"
      - "../recnode:/app/recnode"
