metadata:
  appName: recnode-server
  name: recnode-server
  namespace: media

serviceMonitor:
  enabled: true
  namespace: telemetry
  labels:
    release: kube-prometheus-stack

nodeName: ~

auth:
  secretName: recnode-auth
  tokenKey: bearer-token
