apiVersion: v1
kind: Service
metadata:
  name: stdl-nodeport-main
  namespace: media
spec:
  selector:
    controller: eventsource-controller
    eventsource-name: webhook
    owner-name: webhook
  type: NodePort
  ports:
    - port: 12000
      protocol: TCP
      targetPort: 12000
      nodePort: 30720
