apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: dep
      eventSourceName: webhook
      eventName: {{ .Values.global.name }}
  triggers:
    - template:
        name: stdl-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: {{ .Values.global.name }}-
              spec:
                entrypoint: main
                volumeClaimTemplates:
                  - metadata:
                      name: stdl-ceph
                    spec:
                      storageClassName: {{ .Values.persistence.ceph.storageClass }}
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: {{ .Values.persistence.ceph.requests }}
                imagePullSecrets:
                  - name: {{ .Values.image.pullSecret }}
                arguments:
                  parameters:
                    - name: message
                      value: hello
                templates:
                  - name: main
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
                      env:
                        - name: APP_CONFIG
                          value: "{{`{{inputs.parameters.message}}`}}"
                        - name: OUT_DIR_PATH
                          value: {{ .Values.persistence.nfs.mountPath }}
                        - name: TMP_DIR_PATH
                          value: {{ .Values.persistence.ceph.mountPath }}
                        - name: PY_ENV
                          value: prod
                      volumeMounts:
                        - name: stdl-nfs
                          mountPath: {{ .Values.persistence.nfs.mountPath }}
                        - name: stdl-ceph
                          mountPath: {{ .Values.persistence.ceph.mountPath }}
                      resources:
                        requests:
                          cpu: {{ .Values.resources.requests.cpu }}
                          memory: {{ .Values.resources.requests.memory }}
                    volumes:
                      - name: stdl-nfs
                        persistentVolumeClaim:
                          claimName: {{ .Values.persistence.nfs.pvcName }}
                    tolerations:
                      - effect: NoSchedule
                        operator: Exists
                      - key: CriticalAddonsOnly
                        operator: Exists
                      - effect: NoExecute
                        operator: Exists
          parameters:
            - src:
                dependencyName: dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
