metadata:
  name: stdl-redis
  namespace: media

service:
  nodePort:
    master: 30211
    replica: 30212

redis:
  global:
    storageClass: longhorn
  auth:
    existingSecret: stdl-redis-server
    existingSecretPasswordKey: password
  master:
    service:
      type: ClusterIP
      ports:
        redis: 6379
    persistence:
      enabled: true
      size: 4Gi
    resources:
      requests:
        memory: 1024Mi
      limits:
        memory: 2048Mi
  replica:
    replicaCount: 3
    service:
      type: ClusterIP
      ports:
        redis: 6379
    persistence:
      enabled: true
      size: 4Gi
    resources:
      requests:
        memory: 1024Mi
      limits:
        memory: 2048Mi
