metadata:
  name: stdl-redis
  namespace: media

vault:
  mount: kube
  version: 1
  refreshAfter: 30s
  path: media/stdl/redis
  secretName: stdl-redis-auth

redis:
  global:
    storageClass: longhorn
  auth:
    existingSecret: stdl-redis-auth
    existingSecretPasswordKey: password
  master:
    service:
      type: NodePort
      ports:
        redis: 6379
      nodePorts:
        redis: 30211
    persistence:
      enabled: true
      size: 8Gi
  replica:
    replicaCount: 3
    service:
      type: NodePort
      ports:
        redis: 6379
      nodePorts:
        redis: 30212
    persistence:
      enabled: true
      size: 8Gi
