metadata:
  name: recnode-redis
  namespace: media

service:
  nodePort:
    master: 30211
    replica: 30212

redis:
#  global:
#    storageClass: longhorn
  auth:
    existingSecret: recnode-redis-server
    existingSecretPasswordKey: password
  master:
    service:
      type: ClusterIP
      ports:
        redis: 6379
    persistence:
      enabled: false
#      enabled: true
#      size: 4Gi
    resourcesPreset: none
#    resources:
#      requests:
#        memory: 1024Mi
#      limits:
#        memory: 2048Mi
  replica:
    replicaCount: 6
    service:
      type: ClusterIP
      ports:
        redis: 6379
    persistence:
      enabled: false
#      enabled: true
#      size: 4Gi
    resourcesPreset: none
#    resources:
#      requests:
#        memory: 1024Mi
#      limits:
#        memory: 2048Mi
