metadata:
  name: stdl-redis
  namespace: media
domainName: stdl-redis.rwiv.xyz
tls:
  secretName: stdl-redis-tls

redis:
  global:
    storageClass: rook-ceph-block
  auth:
    existingSecret: stdl-redis-auth
    existingSecretPasswordKey: password
  master:
    service:
      type: NodePort
      ports:
        redis: 6379
      nodePorts:
        redis: 30211
    persistence:
      enabled: true
  replica:
    replicaCount: 3
    service:
      type: NodePort
      ports:
        redis: 6379
      nodePorts:
        redis: 30212
    persistence:
      enabled: false
  tls:
    enabled: true
    authClients: false
    existingSecret: stdl-redis-tls
    certCAFilename: ca.crt
    certFilename: tls.crt
    certKeyFilename: tls.key
