metadata:
  name: stdl-redis
  namespace: media

vault:
  mount: kube
  version: 1
  refreshAfter: 30s
  path: media/stdl/redis
  secretName: stdl-redis-auth

redis:
  global:
    storageClass: longhorn
  auth:
    existingSecret: stdl-redis-auth
    existingSecretPasswordKey: password
  master:
    service:
      type: ClusterIP
      ports:
        redis: 6379
    persistence:
      enabled: true
      size: 4Gi
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
  replica:
    replicaCount: 4
    service:
      type: ClusterIP
      ports:
        redis: 6379
    persistence:
      enabled: true
      size: 4Gi
    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
