metadata:
  name: stdl-proxy
  appName: stdl-proxy
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/stdl
  tag: 0.0.0
  pullSecret: image-pull-secret
affinity: {}
podLabels: {}
nodeName: ~
server:
  replicas: 3
  containerName: stdl-proxy
  service:
    type: ClusterIP
    port: 80
    targetPort: 9084
    nodePort: 30214
  secrets:
    fs:
      name: stdl-fs
      fsNameKey: fs-name
