metadata:
  name: recnode-proxy
  appName: recnode-proxy
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/recnode
  tag: 0.0.0
  pullSecret: image-pull-secret
affinity: {}
podLabels: {}
nodeAlias: ~
server:
  replicas: 2
  containerName: recnode-proxy
  service:
    type: ClusterIP
    port: 80
    targetPort: 9084
    nodePort: 30214
  fs:
    secretName: recnode-fs
    fsNameKey: fs-name
    confKey: fs_conf.yaml
