global:
  name: stdl
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/stdl
  tag: 0.1.13
  pullSecret: image-pull-secret
persistence:
  nfs:
    pvcName: stdl
    storageClass: nfs-main1
    mountPath: /mnt/nfs
    requests: 2000Gi
  ceph:
    storageClass: rook-ceph-block
    mountPath: /mnt/ceph
    requests: 100Gi
resources:
  requests:
    cpu: 40m
    memory: 200Mi
