global:
  name: stdl
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/stdl
  tag: 0.1.5
  pullSecret: image-pull-secret
persistence:
  nfs:
    pvcName: stdl
    storageClass: nfs-nas
    mountPath: /mnt/nfs
    requests: 2000Gi
  ceph:
    storageClass: rook-ceph-block
    mountPath: /mnt/ceph
    requests: 100Gi
