global:
  name: stdl
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/stdl
  tag: 0.1.0
  pullSecret: image-pull-secret
persistence:
  pvcName: nfs-pvc
  mountName: nfs-volume
  storageClass: nfs-content
  mountPath: /mnt/nfs
