global:
  name: stdl-sep
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/stdl
  tag: 0.2.5
  pullSecret: image-pull-secret
gluetun:
  repository: qmcgaw/gluetun
  tag: v3.40
persistence:
  nfs:
    mountPath: /mnt/nfs
  ceph:
    mountPath: /mnt/ceph
    namePrefix: stdl-once-ceph-
    storageClass: rook-ceph-block
    requests: 200Gi
resources:
  requests:
    cpu: 40m
    memory: 200Mi
configMap:
  namePrefix: stdl-once-conf-
  mountPath: /app/conf
secret:
  userKey: user
  passwordKey: password
app:
  rabbitmq:
    host: rabbitmq.infra.svc.cluster.local
    port: 5672
    username: admin
    secretName: rabbitmq-main
    passwordKey: password
  reqType: chzzk_live
  startDelayMs: 0
chzzk:
  live:
    uid: foo
    once: false
  video:
    noList: []
    isParallel: true
    parallelNum: 3
    nonParallelDelayMs: 200
  cookies: ~
afreeca:
  video:
    noList: []
    isParallel: true
    parallelNum: 3
    nonParallelDelayMs: 200
  cookies: ~
jobSuffix: foo
