apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
      sub: {{ .Values.metadata.name }}
      {{ if .Values.nodeAlias }}
      node: {{ .Values.nodeAlias }}
      {{ end }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
        sub: {{ .Values.metadata.name }}
        {{ if .Values.nodeAlias }}
        node: {{ .Values.nodeAlias }}
        {{ end }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{ if .Values.nodeAlias }}
      nodeSelector:
        alias: {{ .Values.nodeAlias }}
      {{ end }}
      containers:
        {{- if .Values.vpn.enabled }}
        - name: gluetun
          image: {{ .Values.gluetun.repository }}:{{ .Values.gluetun.tag }}
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "custom"
            - name: VPN_TYPE
              value: "openvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vpn.credentials.secretName }}
                  key: {{ .Values.vpn.credentials.keys.username }}
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vpn.credentials.secretName }}
                  key: {{ .Values.vpn.credentials.keys.password }}
            - name: OPENVPN_CUSTOM_CONFIG
              value: "/ovpn/{{ .Values.vpn.conf.keys.filename }}"
            - name: DNS_KEEP_NAMESERVER
              value: "true"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
            - name: FIREWALL_INPUT_PORTS
              value: "{{ .Values.server.service.targetPort }}"
          volumeMounts:
            - name: ovpn-conf
              mountPath: "/ovpn/{{ .Values.vpn.conf.keys.filename }}"
              subPath: {{ .Values.vpn.conf.keys.filename }}
              readOnly: true
        {{- end }}
        - name: {{ .Values.server.containerName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          workingDir: "/app"
          command: ["python", "-m", "stdl", "server"]
          {{- if not .Values.vpn.enabled }}
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          {{- end }}
          env:
            - name: PY_ENV
              value: prod
            - name: SERVER_PORT
              value: "{{ .Values.server.service.targetPort }}"
            - name: SERVER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.auth.secretName }}
                  key: {{ .Values.server.auth.tokenKey }}
            {{- if .Values.vpn.enabled }}
            - name: PROXY_ENABLED
              value: "true"
            - name: PROXY_ENDPOINT
              value: {{ .Values.vpn.proxyEndpoint }}
            {{- end }}
            - name: SEG_SIZE_MB
              value: "{{ .Values.server.segSizeMb }}"
            - name: M3U8_RETRY_LIMIT
              value: "{{ .Values.server.reqConf.m3u8RetryLimit }}"
            - name: M3U8_TIMEOUT_SEC
              value: "{{ .Values.server.reqConf.m3u8TimeoutSec }}"
            - name: SEG_TIMEOUT_SEC
              value: "{{ .Values.server.reqConf.segTimeoutSec }}"
            - name: SEG_PARALLEL_RETRY_LIMIT
              value: "{{ .Values.server.reqConf.segParallelRetryLimit }}"
            - name: SEG_FAILURE_THRESHOLD_RATIO
              value: "{{ .Values.server.reqConf.segFailureThresholdRatio }}"
            - name: INTERVAL_WAIT_WEIGHT_SEC
              value: "{{ .Values.server.reqConf.intervalWaitWeightSec }}"
            - name: TMP_DIR_PATH
              value: /app/tmp
            - name: FS_CONFIG_PATH
              value: "/mnt/fs-configs/{{ .Values.server.fs.confKey }}"

{{/*            - name: REDIS_MASTER_HOST*/}}
{{/*              value: {{ .Values.redis.masterHost }}*/}}
{{/*            - name: REDIS_MASTER_PORT*/}}
{{/*              value: "{{ .Values.redis.masterPort }}"*/}}
{{/*            - name: REDIS_REPLICA_HOST*/}}
{{/*              value: {{ .Values.redis.replicaHost }}*/}}
{{/*            - name: REDIS_REPLICA_PORT*/}}
{{/*              value: "{{ .Values.redis.replicaPort }}"*/}}

            - name: REDIS_MASTER_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.client.secretName }}
                  key: {{ .Values.redis.client.hostKey }}
            - name: REDIS_MASTER_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.client.secretName }}
                  key: {{ .Values.redis.client.masterPortKey }}
            - name: REDIS_REPLICA_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.client.secretName }}
                  key: {{ .Values.redis.client.hostKey }}
            - name: REDIS_REPLICA_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.client.secretName }}
                  key: {{ .Values.redis.client.replicaPortKey }}

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.server.secretName }}
                  key: {{ .Values.redis.server.passwordKey }}
            - name: REDIS_POOL_SIZE_LIMIT
              value: "{{ .Values.redis.poolSize }}"
            - name: REDIS_LOCK_EXPIRE_MS
              value: "{{ .Values.redis.data.lockExpireMs }}"
            - name: REDIS_LOCK_WAIT_SEC
              value: "{{ .Values.redis.data.lockWaitSec }}"
            - name: REDIS_LIVE_EXPIRE_SEC
              value: "{{ .Values.redis.data.liveExpireSec }}"
            - name: REDIS_SEG_EXPIRE_SEC
              value: "{{ .Values.redis.data.segExpireSec }}"
            {{- if .Values.proxy.enabled }}
            - name: PROXY_PORT_DOMESTIC
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.proxy.secretName }}
                  key: {{ .Values.proxy.portDomesticKey }}
            - name: PROXY_PORT_OVERSEAS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.proxy.secretName }}
                  key: {{ .Values.proxy.portOverseasKey }}
            - name: PROXY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.proxy.secretName }}
                  key: {{ .Values.proxy.usernameKey }}
            - name: PROXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.proxy.secretName }}
                  key: {{ .Values.proxy.passwordKey }}
            - name: PROXY_RDNS
              value: "{{ .Values.proxy.rdns }}"
            - name: PROXY_USE_MY_IP
              value: "{{ .Values.proxy.useMyIp }}"
            {{- end }}
          volumeMounts:
            - name: fs-configs
              mountPath: "/mnt/fs-configs/{{ .Values.server.fs.confKey }}"
              subPath: {{ .Values.server.fs.confKey }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: fs-configs
          secret:
            secretName: {{ .Values.server.fs.secretName }}
        {{- if .Values.vpn.enabled }}
        - name: ovpn-conf
          secret:
            secretName: {{ .Values.vpn.conf.secretName }}
        {{- end }}
