apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
      sub: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
        sub: {{ .Values.metadata.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.server.containerName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          workingDir: "/app"
          command: ["python", "-m", "stdl", "server"]
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          env:
            - name: PY_ENV
              value: prod
            - name: SERVER_PORT
              value: "{{ .Values.server.service.targetPort }}"
            - name: SEG_SIZE_MB
              value: "{{ .Values.server.segSizeMb }}"
            - name: TMP_DIR_PATH
              value: /app/tmp
            - name: FS_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vault.fs.secretName }}
                  key: {{ .Values.vault.fs.fsNameKey }}
            - name: FS_CONFIG_PATH
              value: /mnt/fs-configs/fs_conf.yaml
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: {{ .Values.redis.passwordKey }}
          volumeMounts:
            - name: fs-configs
              mountPath: /mnt/fs-configs/fs_conf.yaml
              subPath: fs_conf.yaml
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: fs-configs
          secret:
            secretName: {{ .Values.vault.fs.secretName }}
