{{- if .Values.plain.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.plain.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
      sub: {{ .Values.plain.name }}
      {{ if .Values.nodeName }}
      node: {{ .Values.nodeName }}
      {{ end }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
        sub: {{ .Values.plain.name }}
        {{ if .Values.nodeName }}
        node: {{ .Values.nodeName }}
        {{ end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{ if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{ end }}
      containers:
        - name: {{ .Values.server.containerName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          workingDir: "/app"
          command: ["python", "-m", "stdl", "server"]
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          env:
            - name: PY_ENV
              value: prod
            - name: SERVER_PORT
              value: "{{ .Values.server.service.targetPort }}"
            - name: SEG_SIZE_MB
              value: "{{ .Values.server.segSizeMb }}"
            - name: M3U8_RETRY_LIMIT
              value: "{{ .Values.server.reqConf.m3u8RetryLimit }}"
            - name: M3U8_TIMEOUT_SEC
              value: "{{ .Values.server.reqConf.m3u8TimeoutSec }}"
            - name: SEG_TIMEOUT_SEC
              value: "{{ .Values.server.reqConf.segTimeoutSec }}"
            - name: SEG_PARALLEL_RETRY_LIMIT
              value: "{{ .Values.server.reqConf.segParallelRetryLimit }}"
            - name: SEG_FAILURE_THRESHOLD_RATIO
              value: "{{ .Values.server.reqConf.segFailureThresholdRatio }}"
            - name: TMP_DIR_PATH
              value: /app/tmp
            - name: FS_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.fs.name }}
                  key: {{ .Values.server.fs.fsNameKey }}
            - name: FS_CONFIG_PATH
              value: /mnt/fs-configs/fs_conf.yaml
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.auth.secretName }}
                  key: {{ .Values.redis.auth.passwordKey }}
            - name: REDIS_CA_PATH
              value: /mnt/redis-tls/ca.crt
            - name: REDIS_POOL_SIZE_LIMIT
              value: "{{ .Values.redis.poolSize }}"
            - name: REDIS_LOCK_EXPIRE_MS
              value: "{{ .Values.redis.data.lockExpireMs }}"
            - name: REDIS_LOCK_WAIT_SEC
              value: "{{ .Values.redis.data.lockWaitSec }}"
            - name: REDIS_LIVE_EXPIRE_SEC
              value: "{{ .Values.redis.data.liveExpireSec }}"
            - name: REDIS_SEG_EXPIRE_SEC
              value: "{{ .Values.redis.data.segExpireSec }}"
          volumeMounts:
            - name: fs-configs
              mountPath: /mnt/fs-configs/fs_conf.yaml
              subPath: fs_conf.yaml
            - name: redis-tls
              mountPath: /mnt/redis-tls/ca.crt
              subPath: ca.crt
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: fs-configs
          secret:
            secretName: {{ .Values.server.fs.name }}
        - name: redis-tls
          secret:
            secretName: {{ .Values.redis.tls.secretName }}
{{- end }}
