apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.appName }}
    sub: {{ .Values.metadata.name }}
    {{ if .Values.nodeAlias }}
    node: {{ .Values.nodeAlias }}
    {{ end }}
spec:
  selector:
    app: {{ .Values.metadata.appName }}
    sub: {{ .Values.metadata.name }}
    {{ if .Values.nodeAlias }}
    node: {{ .Values.nodeAlias }}
    {{ end }}
  type: {{ .Values.server.service.type }}
  ports:
    - name: {{ .Values.server.service.name }}
      port: {{ .Values.server.service.port }}
      protocol: {{ .Values.server.service.protocol }}
      targetPort: {{ .Values.server.service.targetPort }}
