{{- if .Values.vpn.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vpn.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.appName }}
      sub: {{ .Values.vpn.name }}
      {{ if .Values.nodeName }}
      node: {{ .Values.nodeName }}
      {{ end }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.appName }}
        sub: {{ .Values.vpn.name }}
        {{ if .Values.nodeName }}
        node: {{ .Values.nodeName }}
        {{ end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{ if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{ end }}
      containers:
        - name: gluetun
          image: {{ .Values.gluetun.repository }}:{{ .Values.gluetun.tag }}
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          securityContext:
            capabilities:
              add: [ "NET_ADMIN" ]
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "custom"
            - name: VPN_TYPE
              value: "openvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vpn.nordvpn.credentials.name }}
                  key: {{ .Values.vpn.nordvpn.credentials.keys.username }}
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vpn.nordvpn.credentials.name }}
                  key: {{ .Values.vpn.nordvpn.credentials.keys.password }}
            - name: OPENVPN_CUSTOM_CONFIG
              value: "/ovpn/{{ .Values.vpn.nordvpn.ovpn.keys.filename }}"
            - name: DNS_KEEP_NAMESERVER
              value: "true"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
            - name: FIREWALL_INPUT_PORTS
              value: "{{ .Values.server.service.targetPort }}"
          volumeMounts:
            - name: ovpn-conf
              mountPath: "/ovpn/{{ .Values.vpn.nordvpn.ovpn.keys.filename }}"
              subPath: {{ .Values.vpn.nordvpn.ovpn.keys.filename }}
              readOnly: true
        - name: {{ .Values.server.containerName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          workingDir: "/app"
          command: ["python", "-m", "stdl", "server"]
          env:
            - name: PY_ENV
              value: prod
            - name: SERVER_PORT
              value: "{{ .Values.server.service.targetPort }}"
            - name: PROXY_ENABLED
              value: "true"
            - name: PROXY_ENDPOINT
              value: {{ .Values.vpn.proxyEndpoint }}
            - name: SEG_SIZE_MB
              value: "{{ .Values.server.segSizeMb }}"
            - name: M3U8_RETRY_LIMIT
              value: "{{ .Values.server.reqConf.m3u8RetryLimit }}"
            - name: M3U8_TIMEOUT_SEC
              value: "{{ .Values.server.reqConf.m3u8TimeoutSec }}"
            - name: SEG_TIMEOUT_SEC
              value: "{{ .Values.server.reqConf.segTimeoutSec }}"
            - name: SEG_PARALLEL_RETRY_LIMIT
              value: "{{ .Values.server.reqConf.segParallelRetryLimit }}"
            - name: SEG_FAILURE_THRESHOLD_RATIO
              value: "{{ .Values.server.reqConf.segFailureThresholdRatio }}"
            - name: TMP_DIR_PATH
              value: /app/tmp
            - name: FS_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.fs.name }}
                  key: {{ .Values.server.fs.fsNameKey }}
            - name: FS_CONFIG_PATH
              value: /mnt/fs-configs/fs_conf.yaml
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.auth.secretName }}
                  key: {{ .Values.redis.auth.passwordKey }}
            - name: REDIS_CA_PATH
              value: /mnt/redis-tls/ca.crt
            - name: REDIS_POOL_SIZE
              value: "{{ .Values.redis.poolSize }}"
          volumeMounts:
            - name: fs-configs
              mountPath: /mnt/fs-configs/fs_conf.yaml
              subPath: fs_conf.yaml
            - name: redis-tls
              mountPath: /mnt/redis-tls/ca.crt
              subPath: ca.crt
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: fs-configs
          secret:
            secretName: {{ .Values.server.fs.name }}
        - name: redis-tls
          secret:
            secretName: {{ .Values.redis.tls.secretName }}
        - name: ovpn-conf
          secret:
            secretName: {{ .Values.vpn.nordvpn.ovpn.name }}
{{- end }}
